"""add referral tracking to business_relationships

Revision ID: 03be79a7ecdc
Revises: c77fdd93bcb5
Create Date: 2026-08-24 20:59:11.923974

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '03be79a7ecdc'
down_revision: Union[str, Sequence[str], None] = 'c77fdd93bcb5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('business_relationships', sa.Column('referral_token', sa.String(length=32), nullable=True))
    op.add_column('business_relationships', sa.Column('referral_clicked_at', sa.DateTime(), nullable=True))
    op.add_column('business_relationships', sa.Column('referral_signup_confirmed_at', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_business_relationships_referral_token'), 'business_relationships', ['referral_token'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_business_relationships_referral_token'), table_name='business_relationships')
    op.drop_column('business_relationships', 'referral_signup_confirmed_at')
    op.drop_column('business_relationships', 'referral_clicked_at')
    op.drop_column('business_relationships', 'referral_token')
    # ### end Alembic commands ###
