"""add coupons and coupon_issues

Revision ID: 05ce5c990434
Revises: c391ffacb76f
Create Date: 2026-08-22 19:30:15.696562

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '05ce5c990434'
down_revision: Union[str, Sequence[str], None] = 'c391ffacb76f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('coupons',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('business_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.String(length=1000), nullable=True),
    sa.Column('discount_type', sa.Enum('PERCENTAGE', 'FIXED_AMOUNT', name='coupon_discount_type'), nullable=False),
    sa.Column('discount_value', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('start_at', sa.DateTime(), nullable=True),
    sa.Column('end_at', sa.DateTime(), nullable=True),
    sa.Column('conditions', sa.String(length=500), nullable=True),
    sa.Column('usage_limit', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('DRAFT', 'ACTIVE', 'EXPIRED', 'DISABLED', name='coupon_status'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_coupons_business_id'), 'coupons', ['business_id'], unique=False)
    op.create_table('coupon_issues',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('coupon_id', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(length=12), nullable=False),
    sa.Column('status', sa.Enum('ISSUED', 'REDEEMED', name='coupon_issue_status'), nullable=False),
    sa.Column('issued_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('redeemed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['coupon_id'], ['coupons.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_coupon_issues_code'), 'coupon_issues', ['code'], unique=True)
    op.create_index(op.f('ix_coupon_issues_coupon_id'), 'coupon_issues', ['coupon_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_coupon_issues_coupon_id'), table_name='coupon_issues')
    op.drop_index(op.f('ix_coupon_issues_code'), table_name='coupon_issues')
    op.drop_table('coupon_issues')
    op.drop_index(op.f('ix_coupons_business_id'), table_name='coupons')
    op.drop_table('coupons')
    # ### end Alembic commands ###
    sa.Enum(name='coupon_issue_status').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='coupon_status').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='coupon_discount_type').drop(op.get_bind(), checkfirst=True)
