"""add customer_user_id to coupon_issues and reservations

Revision ID: 2366be8d739f
Revises: a221fefbc6b8
Create Date: 2026-08-24 22:11:52.568019

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2366be8d739f'
down_revision: Union[str, Sequence[str], None] = 'a221fefbc6b8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('coupon_issues', sa.Column('customer_user_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_coupon_issues_customer_user_id'), 'coupon_issues', ['customer_user_id'], unique=False)
    op.create_foreign_key(None, 'coupon_issues', 'users', ['customer_user_id'], ['id'])
    op.add_column('reservations', sa.Column('customer_user_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_reservations_customer_user_id'), 'reservations', ['customer_user_id'], unique=False)
    op.create_foreign_key(None, 'reservations', 'users', ['customer_user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'reservations', type_='foreignkey')
    op.drop_index(op.f('ix_reservations_customer_user_id'), table_name='reservations')
    op.drop_column('reservations', 'customer_user_id')
    op.drop_constraint(None, 'coupon_issues', type_='foreignkey')
    op.drop_index(op.f('ix_coupon_issues_customer_user_id'), table_name='coupon_issues')
    op.drop_column('coupon_issues', 'customer_user_id')
    # ### end Alembic commands ###
