"""add business lon/lat and business_relationships (partner graph)

Revision ID: 2fc2016da33b
Revises: fcb4bf08a0b4
Create Date: 2026-08-22 21:37:46.924418

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2fc2016da33b'
down_revision: Union[str, Sequence[str], None] = 'fcb4bf08a0b4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('business_relationships',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('business_a_id', sa.UUID(), nullable=False),
    sa.Column('business_b_id', sa.UUID(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('reason', sa.String(length=500), nullable=False),
    sa.Column('status', sa.Enum('SUGGESTED', 'INVITED', 'ACCEPTED', 'REJECTED', name='partner_relationship_status'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['business_a_id'], ['businesses.id'], ),
    sa.ForeignKeyConstraint(['business_b_id'], ['businesses.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('business_a_id', 'business_b_id', name='uq_business_relationship_pair')
    )
    op.create_index(op.f('ix_business_relationships_business_a_id'), 'business_relationships', ['business_a_id'], unique=False)
    op.create_index(op.f('ix_business_relationships_business_b_id'), 'business_relationships', ['business_b_id'], unique=False)
    op.add_column('businesses', sa.Column('lon', sa.Float(), nullable=True))
    op.add_column('businesses', sa.Column('lat', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('businesses', 'lat')
    op.drop_column('businesses', 'lon')
    op.drop_index(op.f('ix_business_relationships_business_b_id'), table_name='business_relationships')
    op.drop_index(op.f('ix_business_relationships_business_a_id'), table_name='business_relationships')
    op.drop_table('business_relationships')
    # ### end Alembic commands ###
    sa.Enum(name='partner_relationship_status').drop(op.get_bind(), checkfirst=True)
