"""add unique indexes preventing duplicate transaction links

Revision ID: 5c9e80273880
Revises: 2366be8d739f
Create Date: 2026-08-24 23:14:46.289071

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5c9e80273880'
down_revision: Union[str, Sequence[str], None] = '2366be8d739f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('uq_transactions_coupon_issue_id', 'transactions', ['coupon_issue_id'], unique=True, postgresql_where='coupon_issue_id IS NOT NULL')
    op.create_index('uq_transactions_reservation_id', 'transactions', ['reservation_id'], unique=True, postgresql_where='reservation_id IS NOT NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_transactions_reservation_id', table_name='transactions', postgresql_where='reservation_id IS NOT NULL')
    op.drop_index('uq_transactions_coupon_issue_id', table_name='transactions', postgresql_where='coupon_issue_id IS NOT NULL')
    # ### end Alembic commands ###
