"""add naver_map_url to business_profiles

Revision ID: 7072fb56be56
Revises: c64b4dca26f3
Create Date: 2026-08-24 10:43:00.115447

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7072fb56be56'
down_revision: Union[str, Sequence[str], None] = 'c64b4dca26f3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('business_profiles', sa.Column('naver_map_url', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('business_profiles', 'naver_map_url')
    # ### end Alembic commands ###
