"""add recommendation_clicks table

Revision ID: 851d0be65d94
Revises: 5c9e80273880
Create Date: 2026-08-24 23:59:49.428754

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '851d0be65d94'
down_revision: Union[str, Sequence[str], None] = '5c9e80273880'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('recommendation_clicks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('ai_interaction_id', sa.UUID(), nullable=False),
    sa.Column('entity_id', sa.Uuid(), nullable=False),
    sa.Column('entity_type', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['ai_interaction_id'], ['ai_interactions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recommendation_clicks_ai_interaction_id'), 'recommendation_clicks', ['ai_interaction_id'], unique=False)
    op.create_index(op.f('ix_recommendation_clicks_entity_id'), 'recommendation_clicks', ['entity_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_recommendation_clicks_entity_id'), table_name='recommendation_clicks')
    op.drop_index(op.f('ix_recommendation_clicks_ai_interaction_id'), table_name='recommendation_clicks')
    op.drop_table('recommendation_clicks')
    # ### end Alembic commands ###
