"""add monthly_visitor_estimate to business_profiles

Revision ID: a221fefbc6b8
Revises: 03be79a7ecdc
Create Date: 2026-08-24 21:14:11.528846

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a221fefbc6b8'
down_revision: Union[str, Sequence[str], None] = '03be79a7ecdc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('business_profiles', sa.Column('monthly_visitor_estimate', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('business_profiles', 'monthly_visitor_estimate')
    # ### end Alembic commands ###
