"""add naver_place_url to business_profiles

Revision ID: a5735737104a
Revises: f7ce61892aa6
Create Date: 2026-08-23 09:45:11.448195

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a5735737104a'
down_revision: Union[str, Sequence[str], None] = 'f7ce61892aa6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('business_profiles', sa.Column('naver_place_url', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('business_profiles', 'naver_place_url')
    # ### end Alembic commands ###
