"""add event tracking fields to ai_interactions

Revision ID: c64b4dca26f3
Revises: a5735737104a
Create Date: 2026-08-23 11:09:51.245655

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c64b4dca26f3'
down_revision: Union[str, Sequence[str], None] = 'a5735737104a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ai_interactions', sa.Column('user_message', sa.Text(), nullable=True))
    op.add_column('ai_interactions', sa.Column('reply', sa.Text(), nullable=True))
    op.add_column('ai_interactions', sa.Column('prompt_tokens', sa.Integer(), nullable=True))
    op.add_column('ai_interactions', sa.Column('completion_tokens', sa.Integer(), nullable=True))
    op.add_column('ai_interactions', sa.Column('estimated_cost_usd', sa.Numeric(precision=10, scale=6), nullable=True))
    op.add_column('ai_interactions', sa.Column('prompt_version', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ai_interactions', 'prompt_version')
    op.drop_column('ai_interactions', 'estimated_cost_usd')
    op.drop_column('ai_interactions', 'completion_tokens')
    op.drop_column('ai_interactions', 'prompt_tokens')
    op.drop_column('ai_interactions', 'reply')
    op.drop_column('ai_interactions', 'user_message')
    # ### end Alembic commands ###
