"""add invite_message to business_relationships

Revision ID: ea12a9e60916
Revises: 2fc2016da33b
Create Date: 2026-08-22 21:57:39.925236

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ea12a9e60916'
down_revision: Union[str, Sequence[str], None] = '2fc2016da33b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('business_relationships', sa.Column('invite_message', sa.String(length=1000), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('business_relationships', 'invite_message')
    # ### end Alembic commands ###
