"""add break_time to business_profiles

Revision ID: ee2b8c63953a
Revises: 9c1a5e4f7b21
Create Date: 2026-08-27 16:15:15.275429

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ee2b8c63953a'
down_revision: Union[str, Sequence[str], None] = '9c1a5e4f7b21'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('business_profiles', sa.Column('break_time', sa.String(length=200), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('business_profiles', 'break_time')
    # ### end Alembic commands ###
