"""add takeout_policy to business_profiles

Revision ID: f85fcf8302f6
Revises: 949d5a63ee40
Create Date: 2026-08-24 19:50:30.642929

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f85fcf8302f6'
down_revision: Union[str, Sequence[str], None] = '949d5a63ee40'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('business_profiles', sa.Column('takeout_policy', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('business_profiles', 'takeout_policy')
    # ### end Alembic commands ###
