"""make business owner nullable, add data_source/external_id for claimable listings

Revision ID: fcb4bf08a0b4
Revises: 9896e61377fc
Create Date: 2026-08-22 21:14:08.531022

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fcb4bf08a0b4'
down_revision: Union[str, Sequence[str], None] = '9896e61377fc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('businesses', sa.Column('data_source', sa.String(length=100), nullable=True))
    op.add_column('businesses', sa.Column('external_id', sa.String(length=100), nullable=True))
    op.alter_column('businesses', 'owner_user_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.create_unique_constraint('uq_businesses_external_id', 'businesses', ['external_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_businesses_external_id', 'businesses', type_='unique')
    op.alter_column('businesses', 'owner_user_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_column('businesses', 'external_id')
    op.drop_column('businesses', 'data_source')
    # ### end Alembic commands ###
