# alembic/env.py does `from models import *` so importing everything here
# registers all model classes on Base.metadata.
from .models import (  # noqa: F401
    AiInteraction,
    AiInteractionFeedback,
    Business,
    BusinessCategory,
    BusinessProfile,
    BusinessRelationship,
    BusinessStatus,
    Coupon,
    CouponDiscountType,
    CouponIssue,
    CouponIssueStatus,
    CouponStatus,
    Menu,
    PartnerRelationshipStatus,
    PilotStatus,
    RecommendationClick,
    Reservation,
    ReservationStatus,
    TouristPlace,
    TouristPlaceStatus,
    Transaction,
    TransactionAttribution,
    User,
    UserRole,
)
